runtime: python27
api_version: 1
threadsafe: true
skip_files:
  - node_modules/
  - .git/
  - .idea
  - .vscode
  - public
  - src
  - talk.txt
  - line-viewer.iml
  - parse-test.mjs
  - parse.mjs

handlers:
  - url: /(.*\.[0-9a-zA-Z]+)
    static_files: build/\1
    upload: build/(.*)

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
